server:
  port: 8080
spring:
  application:
    name: d1
  cloud:
    consul:
      port: 8500
      host: localhost
my:
  name: cai
  age: 10

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
