server:
  port: 10000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: d1
#        uri: http://127.0.0.1:8080/
        uri: lb://d1:8080/hello
        predicates:
        - Path=/foo/{segment}

